### ISSUE TITLE
[Feature] Add teardown() hook similar to setup()

### ISSUE THREAD

**Issue by jakubriedl** [storybookjs/test-runner#109]
It would be very useful to have `teardown()` hook similar to `setup()` so we can run code after all stories are tested.

One use-case is to write [github test summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) after tests finish. Which would be super useful for a11y tests. 

But in principle there can be many things that `afterAll` or `teardown` function would be useful.

**Comment by puppybits** [comment]
+1 This is really important for using with test runner to report on results.

**Comment by yannbf** [comment]
Hey there! Thanks for opening this issue. I'll close it as a duplicated of #251 so the discussions can happen in the same place.
