### ISSUE TITLE
Add support to `--reporters` flag from Jest

### ISSUE THREAD

**Issue by rhuanbarreto** [storybookjs/test-runner#129]
This feature will enable me report test results in a junit file format using the flags:

`--reporters=default --reporters=jest-junit`

This will add the possibility to integrate the test runner more tightly in my CI

**Comment by rhuanbarreto** [comment]
`nyc` works only for code coverage results. Those flags are for Jest reporting the test results for each story run and its play functions.

**Comment by penx** [comment]
@yannbf for the nyc report, the default is `text`, so can't we remove this from

https://github.com/storybookjs/test-runner/blob/380ed6c3ad6a02b0b71d9b9c55b097e9fbd63fee/bin/test-storybook.js#L66

Then this would respect the reporter from any .nycrc file if present?

Alternatively perhaps the nyc reporter could be a config option? I should have time to work on this if it's wanted.

**Comment by rhuanbarreto** [comment]
For me v0.6.4 solves the issue. I'm closing it then.
