### ISSUE TITLE
Test runner does not recognize files other than "*.stories.*"

### ISSUE THREAD

**Issue by amywangg** [storybookjs/test-runner#137]
Using @storybook/test-runner v0.3.0 and jest v27
In my main.js my stories are described as such and it runs fine with yarn storybook
<img width="449" alt="image" src="https://user-images.githubusercontent.com/40084360/177359880-59f9fbdc-edce-404c-b03f-6b090242f89c.png">

I have multiple story files and when I run test-runner for just *.stories.tsx it works fine
<img width="509" alt="image" src="https://user-images.githubusercontent.com/40084360/177360149-141a6eda-3fb8-435d-a5a5-47bd1a0b0976.png">
As soon as I use
<img width="270" alt="image" src="https://user-images.githubusercontent.com/40084360/177360084-3c5355b7-fcbe-4820-b2f4-8fbe8a262fb9.png">
I get this error 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/40084360/177361318-49b7bc3f-dd8e-4b12-816c-ee0beb3d47bc.png">

However I have tried, as a test, to change the name of the file from Accordion.fixtures.tsx -> Accordion.stories.tsx (there wasn't one existing) and it works fine. Same holds true for Accordion.examples.tsx -> Accordion.stories.tsx 

Wondering what might be the issue....

**Comment by amywangg** [comment]
Fixed by adding transform options in `test-runner-jest.config.js`

<img width="679" alt="image" src="https://user-images.githubusercontent.com/40084360/177398835-553f0e2f-f51d-475b-a35d-ce14ad186400.png">

Though this is still a bug.

**Comment by gabrielperales** [comment]
Hi, I faced the same issue, and I explained here how I fixed it https://github.com/storybookjs/test-runner/issues/249.

I was coming to open an issue to add that documentation to the README or to find a way to fix it.

**Comment by yannbf** [comment]
Hey @gabrielperales thanks for that! Would you mind making a PR to introduce some documentation for this? Thank you so much <3

**Comment by StephanBijzitter** [comment]
I just ran into this as well.

`getJestConfig` returns a proper value for`testMatch` (which for me to is to write it as `.story.tsx`), but the `transform` value still references `.stories`.

```
  testMatch: [ '<rootDir>/src\\react\\**\\*.stories.tsx' ],
  transform: {
    '^.+\\.stories\\.[jt]sx?$': '@storybook/test-runner/playwright/transform',
    '^.+\\.[jt]sx?$': <redacted>\\.yarn\\__virtual__\\@swc-jest-virtual-61723854d4\\0\\cache\\@swc-jest-npm-0.2.26-890d01518c-771821ed08.zip\\node_m
odules\\@swc\\jest'
  },

```

Perhaps the config could take `testMatch`, strip the `<rootDir>/`, convert the globs to regular expressions ([glob-to-regexp](https://www.npmjs.com/package/glob-to-regexp)?) and add them to the `transform` object?

**Comment by StephanBijzitter** [comment]
Didn't get the above to work easily, but this works for me (and maybe for more people):

.storybook/main.js:
```js
stories: ["../src/react/**/*.story.tsx"],
```

test-runner-jest.config.js:
```js
const {getJestConfig} = require('@storybook/test-runner');

const jestConfig = getJestConfig();

/**
 * @type {import('@jest/types').Config.InitialOptions}
 */
module.exports = {
    ...jestConfig,
    transform: jestConfig.testMatch.reduce((result, matcher) => {
        const transformMatcher = matcher
            .replace(/(^.+?\*)(\.\w+\.\w+)/, '$2$')
            .replace(/\./g, '\\.');

        return {
            [transformMatcher]: '@storybook/test-runner/playwright/transform',
            ...result
        };
    }, jestConfig.transform)
};

```
