### ISSUE TITLE
[Question] After ejecting and using testEnvironmentOptions, how do you propagate back CLI commands?

### ISSUE THREAD

**Issue by VickyKoblinski** [storybookjs/test-runner#140]
Senario:

I needed to eject the jest config because I needed to add a launch argument to get my fonts to render correctly in chromium on ubuntu. 

```
const { getJestConfig } = require("@storybook/test-runner");

module.exports = {
  // The default configuration comes from @storybook/test-runner
  ...getJestConfig(),
  /** Add your own overrides below
   * @see https://jestjs.io/docs/configuration
   */
  testEnvironmentOptions: {
    "jest-playwright": {
      launchOptions: {
        args: [
          "--font-render-hinting=none",
        ],
      },
      collectCoverage: true,
    },
  },
};
```

However now some CLI commands arguments aren't passed into testEnvironmentOptions like `--browsers` or `--coverage`. I worked around coverage by setting that to always-true but I don't know how to deal with the browsers. I could create environment variables and pass them in, but it seems like the solution should either be that the launchOptions are merged with the CLI commands or that there's another way.

I might be missing something like that the CLI command already environment variables. :)

**Comment by VickyKoblinski** [comment]
Well duh, you go look at what getJestConfig is doing and replicate it :) 

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const { getJestConfig } = require("@storybook/test-runner");

module.exports = {
  // The default configuration comes from @storybook/test-runner
  ...getJestConfig(),
  /** Add your own overrides below
   * @see https://jestjs.io/docs/configuration
   */
  testEnvironmentOptions: {
    "jest-playwright": {
      browsers: process.env.TEST_BROWSERS.split(",")
        .map(p => p.trim().toLowerCase())
        .filter(Boolean),
      collectCoverage: process.env.STORYBOOK_COLLECT_COVERAGE === "true",
      launchOptions: {
        args: ["--font-render-hinting=none"],
      },
    },
  },
};
```

**Comment by yannbf** [comment]
Hey @VickyKoblinski thanks for opening this issue! Sorry you went through it, but I'm happy you managed!

Although it's great you found that solution, it wasn't trivial and we can possibly do better on our side. One could either fully override the configuration, or merge it so they get everything from the original config + only certain custom bits.

> Well duh, you go look at what getJestConfig is doing and replicate it :)
> 
> ```js
> /* eslint-disable @typescript-eslint/no-var-requires */
> const { getJestConfig } = require("@storybook/test-runner");
> 
> module.exports = {
>   // The default configuration comes from @storybook/test-runner
>   ...getJestConfig(),
>   /** Add your own overrides below
>    * @see https://jestjs.io/docs/configuration
>    */
>   testEnvironmentOptions: {
>     "jest-playwright": {
>       browsers: process.env.TEST_BROWSERS.split(",")
>         .map(p => p.trim().toLowerCase())
>         .filter(Boolean),
>       collectCoverage: process.env.STORYBOOK_COLLECT_COVERAGE === "true",
>       launchOptions: {
>         args: ["--font-render-hinting=none"],
>       },
>     },
>   },
> };
> ```

Ideally you should not just replicate the code because it might change over time, so what you can do is:

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const { getJestConfig } = require("@storybook/test-runner");

const originalConfig = getJestConfig()
module.exports = {
  // The default configuration comes from @storybook/test-runner
  ...originalConfig,
  /** Add your own overrides below
   * @see https://jestjs.io/docs/configuration
   */
  testEnvironmentOptions: {
    "jest-playwright": {
      ...originalConfig.testEnvironmentOptions["jest-playwright"],
      launchOptions: {
        args: ["--font-render-hinting=none"],
      },
    },
  },
};
```

Or, because it might be tricky always having to spread bits of the config, you could use a [deepMerge](https://www.npmjs.com/package/deepmerge) library (or maybe we can provide this function from the test runner itself):

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const { getJestConfig } = require("@storybook/test-runner");
const merge = require("deepmerge");

// The default configuration comes from @storybook/test-runner
module.exports = merge(getJestConfig(), {
  /** Add your own overrides below
   * @see https://jestjs.io/docs/configuration
   */
  testEnvironmentOptions: {
    "jest-playwright": {
      launchOptions: {
        args: ["--font-render-hinting=none"],
      },
    },
  },
};
```

We could also potentially change the ‘getJestConfig‘ function to receive an object and deep merge with it, this way it's even simpler.

WDYT @shilman?
