### ISSUE TITLE
[Bug] Storybook Interaction Test Passes but fails in the Test Runner

### ISSUE THREAD

**Issue by brendon-aung** [storybookjs/test-runner#151]
### Describe the bug

Storybook interaction test passes on storybook itself but keeps failing when it is run via the test runner as it cannot find the text I am quering. This might be because of the async nature of `findByRole`.

### Steps to reproduce the behavior

Create a storybook test and use async `findBy` queries in the `play` function and test it works when running on Storybook. Then test via the test runner to see if it fails.

### Expected behavior

The test runner should pass the interaction test if the storybook's interaction test passes as well.

### Screenshots and/or logs

This is the play test code I am using:

```
const Template: ComponentStory<typeof Cta> = ({ ...args }) => (
  <Box bg="colorway.background" p={4}>
    <Cta {...args}>Click me</Cta>
  </Box>
)

export const ClickButton = Template.bind({})
ClickButton.args = {
  theme: 'primary',
  size: 'regular',
  cta: {
    text: 'Click Me',
    url: 'https://google.com',
    target: '_blank'
  },
  radius: 5
}
ClickButton.play = async ({ args, canvasElement }) => {
  const canvas = within(canvasElement)
  const button = await canvas.findByRole('link', { name: 'Click Me' })
  await userEvent.click(button)
  await expect(args.onClick).toHaveBeenCalled()
}
```

Storybook interaction test passes:

![Screen Shot 2022-07-21 at 3 54 45 pm](https://user-images.githubusercontent.com/106134795/180150049-0e84eb66-3062-4de4-b4fe-1d4565e8e463.png)

But the same test fails in test runner:

![Screen Shot 2022-07-21 at 3 54 54 pm](https://user-images.githubusercontent.com/106134795/180150133-28761231-7eff-4b93-a38d-caedf7364841.png)

Upon clicking the link, I am taken to the browser and the logs indicate that the component itself is not rendering for some reason:

![Screen Shot 2022-07-21 at 3 58 07 pm](https://user-images.githubusercontent.com/106134795/180150211-7c8c31d4-df38-4ed5-8109-bd6dc8b99e64.png)

### Environment

 - OS: macOS 12.4
 - Node.js version: 18.4.0
 - NPM version: 8.12.1
 - Browser (if applicable): screenshots from Firefox, but happens on Chrome as well.
 - Browser version (if applicable): N/A
 - Device (if applicable): MacBook Pro (14-inch, 2021) M1

### Additional context

This is a gatbsy web app so unsure if its gatbsy related.

**Comment by nagisaando** [comment]
I'm having the same issue.

I'm using 
-  "@storybook/vue3": "^6.5.9",
-  "@storybook/test-runner": "^0.5.0",
- "@storybook/jest": "^0.0.10",
- "@storybook/testing-library": "^0.0.13",
- "@storybook/builder-vite": "^0.1.39",

**Comment by brendon-aung** [comment]
The issue was caused by an incompatible library that prevented 'canvas mode' from rendering the component correctly. This is not due to storybook itself.
