### ISSUE TITLE
[Q] Allow custom directory for test-runner.js instead of default .storybook?

### ISSUE THREAD

**Issue by moviedo** [storybookjs/test-runner#156]
I'm currently working with [nuxt-storybook](https://storybook.nuxtjs.org/) and I have integrated the test-runner with my project. As nuxt-storybook generates storybook configurations within a custom directory, `.nuxt-storybook/storybook` I was wondering if it's possible to change the directory location for the test-runner.js file?

**Comment by yannbf** [comment]
Hey @moviedo thanks for opening this issue.
Yes it's possible, you can use the --config-dir  flag just like the one in storybook!

https://github.com/storybookjs/test-runner#cli-options

I'll be closing this issue but let me know if it doesn't work for you. Thanks!

**Comment by moviedo** [comment]
I meant to ask if there is a separate flag for just the test-runner.js file different from the configuration directory. nuxt-storybook generates the configuration directory and the different config file needs for integration with nuxtjs, but this also means that sometimes the .nuxt-storybook directory is overwritten. I need something where the configuration directory and the test-runner.js live in different places.

I'm already using --config-dir `"storybook:test": "test-storybook --config-dir .nuxt-storybook/storybook"`

**Comment by yannbf** [comment]
Hey @moviedo now I understand what's going on, thanks a lot for explaining further!

That seems like a feature request related to supporting nuxt storybook projects. I'm not experienced with its setup to know if this would be enough, honestly, but we can try! Can you open another issue for a feature request to specify this use case, with maybe a small reproduction? Then we could experiment on. 

For now, you could work around this by using your own manual config in your nuxt storybook:
https://storybook.nuxtjs.org/advanced/manual-setup

And from there you could add the test runner file, which would be picked up automatically.

**Comment by moviedo** [comment]
I have the project working, but had to add some hacky items to get it working. I'll try to setup a codesandbox to display the issue.
