### ISSUE TITLE
Request for jest cli option --ci

### ISSUE THREAD

**Issue by dylanmoz** [storybookjs/test-runner#159]
`--ci` would be useful to use in CI environments so that the test fails if new snapshots are introduced that have not been committed yet.

https://jestjs.io/docs/cli#--ci

**Comment by yannbf** [comment]
Thank you for your request @dylanmoz! Thanks to @italoteix's contribution, this is now released in [v0.9.0](https://github.com/storybookjs/test-runner/releases/tag/v0.9.0)!
