### ISSUE TITLE
[Bug] @storybook/test-runner@npm:0.7.0 doesn't provide jest-environment-node

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/test-runner#183]
### Describe the bug

Yarn shows a warning when adding `@storybook/test-runner`

### Steps to reproduce the behavior

1. Add `@storybook/test-runner` to a repo

### Expected behavior

No missing peer dependency warning from jest dependencies

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/49354825/187014653-8f125332-cbe1-421b-8fbf-d258b60a004d.png)

### Environment

 - OS: Windows 11
 - Node.js version: 16.14.2
 - NPM version: 8.5.0
 - Browser (if applicable): [e.g. chrome, safari]
 - Browser version (if applicable): [e.g. 22]
 - Device (if applicable): [e.g. iPhone6]

**Comment by iDuuck** [comment]
<img width="466" alt="CleanShot 2022-09-21 at 14 14 07@2x" src="https://user-images.githubusercontent.com/325241/191500968-80bc930e-45ce-45c3-92c8-89b9fb34ff3a.png">

For me it's also missing the jest-circus package.
