### ISSUE TITLE
[Feature] Standalone stories.json mode

### ISSUE THREAD

**Issue by shilman** [storybookjs/test-runner#23]
Currently, the test runner works by transforming CSF files into Jest tests. This is great because you can edit your stories & re-run your tests interactively.

However, sometimes all you have is a link to a publicly hosted storybook. If we had a `--stories-json` mode that could transform `stories.json` into a set of tests, then you could run tests against any Storybook with zero configuration.

**Comment by yannbf** [comment]
Fixed in #31
