### ISSUE TITLE
Add an option to exclude a test

### ISSUE THREAD

**Issue by grybykm** [storybookjs/test-runner#247]
**Summary**
Add an option to exclude a test. By saying that I mean to neither generate nor run a test.

**Context**
A reason for that is to speed up test execution. Spawning a browser, a page, and opening it takes a noticeable amount of time.

I have around 1000 stories but need to test only 200 of them. Running tests in chromium and webkit takes more than 5 minutes to just open and close a browser.

**Request**
Add an option to prevent the browser from starting if the condition is not fulfilled. This seems to be a non-breaking change.

```js
module.exports = {
  setup() {},
  // please choose a more suitable name if you like
  async beforeRun(context) {
    if (context.id.included('foobar')) {
       return true; // prevents the test from being generated
    }
    // run a test as before
  },
  async preRender(page, context) {},
  async postRender(page, context) {},
};
```

**Comment by yannbf** [comment]
Hey @grybykm ! I wonder if you can just [eject your configuration](https://github.com/storybookjs/test-runner#ejecting-configuration) and use Jest options to filter out the stories of which you don't want to test? This way the tests will not be generated.

**Comment by grybykm** [comment]
Hey @yannbf, thank you for the suggestion. 

Sorry to say I didn't find a solution that worked out for me. Let me be more specific:

I've tried to use `testPathIgnorePatterns` but it only takes the file name into account which doesn't satisfy my needs.
I've also tried to use `testNamePattern: '.*/TestStory.*'` but it causes the following error:
```
 FAIL  ../../../../../private/var/folders/tf/_z7gp44s5m96gk7drl6sgzgr0000gp/T/ce39d309a31de4e8369b6f40f8583488/base-avatar-variants.test.js
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'goto')

      at setupPage (node_modules/@storybook/test-runner/dist/cjs/setup-page.js:49:14)
      at CustomEnvironment.setup (node_modules/@storybook/test-runner/playwright/custom-environment.js:9:5)
```

**Comment by grybykm** [comment]
@yannbf do you need some extra info or do you have something else in mind?

**Comment by grybykm** [comment]
Any update on this issue?

**Comment by yannbf** [comment]
Hey @grybykm I believe you can achieve what you're looking for with a [custom filter file](https://jestjs.io/docs/cli#--filterfile):

```
// test-runner-jest.config.js
const { getJestConfig } = require('@storybook/test-runner')

module.exports = {
  // The default configuration comes from @storybook/test-runner
  ...getJestConfig(),
  filter: '<rootDir>/filter.js', // <-- add this
}
```

and the filter file:
```js
// filter.js (or whatever name you like)
module.exports = testPaths => {
  const allowedPaths = testPaths
    .filter(fileName => {
      return fileName.includes('Card')
    })
    .map(test => ({ test }));

  return {
    filtered: allowedPaths,
  };
};
```

**Comment by grybykm** [comment]
@yannbf thanks for replying!

This indeed might help a bit. One big issue for me with this is that it doesn't take into ac account the exported story names.

For example, a file with the name TestStory might export two stories StoryA and StoryB. I might wanna test only test StoryB and don't want a browser to start only to check that my story name doesn't match the pattern.

Do you have any ideas on how this can be achieved?

**Comment by yannbf** [comment]
Hey everyone! We just released a test filtering feature in the test-runner v0.15.0, [which you can read here](https://github.com/storybookjs/test-runner#filtering-tests-experimental).

Please try it out and provide feedback! Thank you!
