### ISSUE TITLE
[Bug] act(...) is not supported in production builds of React.

### ISSUE THREAD

**Issue by ild0tt0re** [storybookjs/test-runner#253]
### Describe the bug

When i run the test-runner against a built version of my stories and a `@storybook/testing-library` event is executed in a storybook **play** function, the following error come out:
```
Message:
     act(...) is not supported in production builds of React.
```

### Steps to reproduce the behavior

1. create a story with at least one event from `@storybook/testing-library`, like `userEvent.click`:
```
ExampleStory.play = async ({ canvasElement }) => {
  const canvas = within(canvasElement)
  const filterEl = await canvas.findByText(/filter/i)
  // the error will be on this event because the testing-library lib auto-wrap in act() the "unit of interaction"
  await userEvent.click(filterEl) 
  const clearFilterElement = await canvas.findByText(/clear filter/i)
  await expect(clearFilterElement).toBeInTheDocument()
}
```

2. I build the stories with `pnpm exec nx build-storybook design-system`
3. Then I serve the static files with `pnpm exec serve dist/storybook/design-system -l 4428`
4. and at the end I run the test-runner against my running service `pnpm exec test-storybook --url "http://127.0.0.1:4428" -c "libs/design-system/.storybook"`
5. See error

### Expected behavior

The `@storybook/test-runner` should successfully execute code from `@storybook/testing-library` even for the built version of the stories.

### Screenshots and/or logs

<img width="1216" alt="act-error" src="https://user-images.githubusercontent.com/1527913/215123073-4642d8f1-7506-4c0c-a4a4-ab9907705d74.png">

### Node modules

- react 18.2.0
- storybook 7.0.0-beta.35
- @storybook/test-runner 0.10.0-next.5
- @storybook/testing-library 0.0.14-next.1

### Environment

 - OS: **macOS Ventura 13.2**
 - Node.js version: **18.13.0**
 - NPM version: pnpm **7.26.0**
 - Browser (if applicable): **Google Chrome**
 - Browser version (if applicable): **109**
 - Device (if applicable): **Macbook Pro 13 M2 2022**

### Additional context

I run storybook as a react **Nextjs lib** in an **Nx workspace**

**Comment by ild0tt0re** [comment]
@yannbf 

The test-runner seems not to have support for react 18, because the unstable_act function in **react.production.min.js** `throw new Error`.
I patched the module with `pnpm patch` replacing it with a simple `console.log` and now work as expected.
I would avoid to patch the react module, do you have some hints?
Thanks!

**Comment by jonwalstedt** [comment]
Hi @ild0tt0re I am having the same issue, do you mind sharing the patch as a workaround?

**Comment by jonwalstedt** [comment]
I tried the workaround but it did not work for me, the userEvents is not being triggered even though i replaced the throw with a console.log as described above. As far as I can tell this is currently making it impossible to run the CI pipline with Storybook 7 and @storybook/testing-library

**Comment by yannbf** [comment]
Hey @jonwalstedt @ild0tt0re we run daily tests on many Storybooks (Including Next.js, React with Webpack and React with Vite), all with a component that has a play function using `@storybook/testing-library`, all of which are tested in prod mode (built then served) and none of them has ever reported that issue 🤔 
I also just created a react sandbox and tried to reproduce the issue, but couldn't. Please share a minimal repro if you have, that'd be highly appreciated.

The only situation I ever stumbled upon where this issue happens, is when users don't import from `@storybook/testing-library`, but end up importing from `@testing-library/react`, `@testing-library/user-event` or `@testing-library/dom` instead.

**Comment by jonwalstedt** [comment]
Oh, yeah that works a lot better - I went through the code now and saw that my IDE has been adding imports from the wrong package. Thanks a lot for the help @yannbf!

**Comment by ctanner-move** [comment]
note for anyone coming to this later, @storybook/testing-library is now @storybook/test
