### ISSUE TITLE
[Bug] Typings for custom Jest matchers

### ISSUE THREAD

**Issue by donaldpipowitch** [storybookjs/test-runner#269]
### Describe the bug

I tried to follow the current docs for all the prereleases of Storybook and the Test Runner, but I think the current setup does not fully cover TypeScript. The custom matchers like `toBeInTheDocument` are not known.

### Steps to reproduce the behavior

1. Clone https://github.com/donaldpipowitch/storybook-testrunner-example.
2. `$ pnpm install && pnpm lint`

### Expected behavior

`toBeInTheDocument` should be known.

### Additional context

You can workaround this by installing `@types/testing-library__jest-dom`, but this puts Jest on the global namespace and as far as I can tell Jest should always be imported from `@storybook/jest`, correct?

**Comment by yannbf** [comment]
Hey @donaldpipowitch !
Thanks for providing a repro. This is a common issue with testing-library (in general) in pnpm repositories, given how pnpm does not hoist packages by default. Please check the instructions here to fix that, and feel free to reopen this issue if they didn't fix your problem: https://github.com/storybookjs/storybook/discussions/16858#discussioncomment-4582481

Thank you!

**Comment by donaldpipowitch** [comment]
Thank you very much! I would have never assumed this is an issue related to pnpm.

**Comment by donaldpipowitch** [comment]
Not sure if this could somehow be cover in the Storybook ESLint rules if a pnpm lock file can be found 🤔

**Comment by david-morris** [comment]
I'm having this behavior despite using yarn and having successfully hoisted the types package:
```
=> Found "@types/testing-library__jest-dom@5.14.1"
info Reasons this module exists
   - "@storybook#jest#@testing-library#jest-dom" depends on it
   - Hoisted from "@storybook#jest#@testing-library#jest-dom#@types#testing-library__jest-dom"
```

I'm going to gather more information about this before filing the same bug.
