### ISSUE TITLE
[Bug] Coverage add on will not run if main config file is using Typescript

### ISSUE THREAD

**Issue by elliotgonzalez123** [storybookjs/test-runner#270]
### Describe the bug

Coverage add on will not run if main config file is using Typescript

### Steps to reproduce the behavior

1. Run npm run test-storybook -- --coverage
2. If your main config file is main.ts, you will get the following error:

`Unexpected token, expected "from"`

3. Change main.ts to main.js and use module.exports syntax, coverage report now works as expected.

### Expected behavior

Coverage report should run even if main config is a TS file.

### Environment

 - NextJS 13
 - Storybook v7 beta 55

**Comment by shilman** [comment]
@yannbf are you able to repro this?

**Comment by shilman** [comment]
I repro'd this in https://github.com/RocketCommunicationsInc/astro but with an ESM main.js -- somehow `serverRequire` isn't working in the project

**Comment by shilman** [comment]
@elliotgonzalez123 Make sure you have `@storybook/test-runner@next` installed, not `latest`

In my case, even though I had the `@next` dependency in my `package.json`, it was installing the `@latest` version in `node_modules`. Deleting `package-lock` and `node_modules` and reinstalling fixed it.

**Comment by yannbf** [comment]
Hey @elliotgonzalez123, thanks for reporting this. I wonder if you're using the prerelease of the test-runner, which is Storybook 7 compatible? The test-runner uses utilities from Storybook, and Storybook 7 has improved the way it resolves the main.js file. I'll close this issue but feel free to open if it still happens with `@storybook/test-runner@next`. Thank you!
