### ISSUE TITLE
[Bug] Can't run test-runner on playwright's offical docker images > 1.24.2

### ISSUE THREAD

**Issue by prewk** [storybookjs/test-runner#291]
### Describe the bug

Playwright supplies [docker images](https://playwright.dev/docs/docker) with browsers + deps pre-installed. These are very useful in CI.

Up to and including version 1.24.2 it works fine to run `test-storybook --url [...]`. Next minor 1.25.2 and all versions above produce this error:

```
57Error: Executable doesn't exist at /ms-playwright/chromium-1005/chrome-linux/chrome
58╔═════════════════════════════════════════════════════════════════════════╗
59║ Looks like Playwright Test or Playwright was just installed or updated. ║
60║ Please run the following command to download new browsers:              ║
61║                                                                         ║
62║     npx playwright install                                              ║
63║                                                                         ║
64║ <3 Playwright Team                                                      ║
65╚═════════════════════════════════════════════════════════════════════════╝ Failed to launch browser.
```

Running `npx playwright install` doesn't help (it's not supposed to be needed with that image for the record, the official playwright image has deps and browers pre-installed).

### Steps to reproduce the behavior

1. Run `test-storybook` in playwright's docker image tagged `v1.24.2-focal` - Success
2. Run `test-storybook` in playwright's docker image tagged `v1.25.2-focal` - Failure

### Expected behavior

`test-storybook` shouldn't pose special requirements on the playwright versions, or at least clarify what they are.

### Screenshots and/or logs

```
[test-storybook] Detected a remote Storybook URL, running in index json mode. To disable this, run the command again with --no-index-json
57Error: Executable doesn't exist at /ms-playwright/chromium-1005/chrome-linux/chrome
58╔═════════════════════════════════════════════════════════════════════════╗
59║ Looks like Playwright Test or Playwright was just installed or updated. ║
60║ Please run the following command to download new browsers:              ║
61║                                                                         ║
62║     npx playwright install                                              ║
63║                                                                         ║
64║ <3 Playwright Team                                                      ║
65╚═════════════════════════════════════════════════════════════════════════╝ Failed to launch browser.
66    at executablePathOrDie (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/server/registry/index.js:297:15)
67    at Object.executablePathOrDie (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/server/registry/index.js:313:43)
68    at Chromium._launchProcess (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/server/browserType.js:204:39)
69    at async Chromium._innerLaunch (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/server/browserType.js:131:9)
70    at async Chromium._innerLaunchWithRetries (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/server/browserType.js:109:14)
71    at async ProgressController.run (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/server/progress.js:101:22)
72    at async Chromium.launch (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/server/browserType.js:84:21)
73    at async BrowserServerLauncherImpl.launchServer (/builds/redacted/service/frontend/frontend/node_modules/playwright-core/lib/browserServerImpl.js:49:21)
74    at async PlaywrightRunner.launchServer (/builds/redacted/service/frontend/frontend/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:69:44)
75    at async PlaywrightRunner.getTests (/builds/redacted/service/frontend/frontend/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:90:36)
```

**Comment by prewk** [comment]
After poking around a bit I can get it to work in some environments and not in others. Does anyone know what/where decides exactly which version of chrome it'll target? Because `chromium-1005` doesn't exist in the image, but a newer version does.

So I'm guessing something somewhere is having some cache troubles. I can actually solve it via symlinking so it thinks it runs the old version, when it in fact runs the new.

**Comment by labmorales** [comment]
The browsers are defined in a JSON file on playwright-core@1.32.2/node_modules/playwright-core/browsers.json and in my case if I change chromium from:

`{
      "name": "chromium",
      "revision": "1055",
      "installByDefault": true,
      "browserVersion": "112.0.5615.29"
    },`

To:
`
    {
      "name": "chromium",
      "revision": "1064",
      "installByDefault": true,
      "browserVersion": "114.0.5735.35"
    },
`

it fixes the tests.

**Comment by labmorales** [comment]
Noticed that the issue was due PNPM or some other lock file getting an older version o Playwright.

I forced the new version via overrides and now it's working:

```
  "pnpm": {
    "overrides": {
      "@storybook/test-runner@0.9.4<playwright": "~1.34.3"
    }
```
