### ISSUE TITLE
[Bug] Using TypeScript or ESModules for test-runner.ts does not work

### ISSUE THREAD

**Issue by iamzapata** [storybookjs/test-runner#293]
### Describe the bug

When using Storybook v7 and trying the `test-runner.ts` examples in[accessibility-testing](https://storybook.js.org/docs/react/writing-tests/accessibility-testing), you encounter one these issues:

#### Using Typescript 

running `npm run test-storybook` with a `.storybook/test-runner.ts` fails

**test-runner.ts**
```typescript

import { injectAxe, checkA11y } from 'axe-playwright';

import type { TestRunnerConfig } from '@storybook/test-runner';

/*
 * See https://storybook.js.org/docs/react/writing-tests/test-runner#test-hook-api-experimental
 * to learn more about the test-runner hooks API.
 */
const a11yConfig: TestRunnerConfig = {
  async preRender(page) {
    await injectAxe(page);
  },
  async postRender(page) {
    await checkA11y(page, '#storybook-root', {
      detailedReport: true,
      detailedReportOptions: {
        html: true,
      },
    });
  },
};

export default a11yConfig
```

```javascript
SyntaxError: ...test-runner.ts: Unexpected token, expected "from" (5:12)

5 | import type { TestRunnerConfig } from '@storybook/test-runner'
                ^
```

#### Using ESModules
running `npm run test-storybook` with a `.storybook/test-runner.js` fails

**test-runner.js**
```javascript
import { injectAxe, checkA11y } from 'axe-playwright';

/*
 * See https://storybook.js.org/docs/react/writing-tests/test-runner#test-hook-api-experimental
 * to learn more about the test-runner hooks API.
 */
const a11yConfig: TestRunnerConfig = {
  async preRender(page) {
    await injectAxe(page);
  },
  async postRender(page) {
    await checkA11y(page, '#storybook-root', {
      detailedReport: true,
      detailedReportOptions: {
        html: true,
      },
    });
  },
};

export default a11yConfig
```

```javascript
Jest encountered an unexpected token

...

Fest failed to parse a file.

...

Details:

import { injectAxe, checkA11y } from 'axe-playwright'
^^^^^^

SyntaxError: Cannot use import statement outside of a module
```

### Steps to reproduce the behavior

1. Setup a simple react/storybook project
2. Set up storybook with test runner
3. Add a `.storybook/test-runner.ts` file
4. Try one of the examples from [accessibility-testing](https://storybook.js.org/docs/react/writing-tests/accessibility-testing)
5. run `npm run test-storybook`
6. See error

### Expected behavior

Using one of the examples from [accessibility-testing](https://storybook.js.org/docs/react/writing-tests/accessibility-testing) should work out of the box if you're running storybook v7

### Environment

 - OS: mac
 - Node.js version: v18.14.2
 - NPM version: 9.5.0

**Comment by Janus451** [comment]
I have the exact same issue. Just using Vue instead of React.

**Comment by Harkunwar** [comment]
Same issue here as well!

**Comment by Andjag** [comment]
Same issue, tried setting this up with React according to the docs on SB v7 and ended up here.

**Comment by m7kvqbe1** [comment]
Same problem here

**Comment by Harkunwar** [comment]
I tried using the latest release `0.11.0-future.1` and it seems like the issue does not happen there. Only with `0.10.0`. Should automatically be fixed once it's released then!

**Comment by Andjag** [comment]
> Harkunwar

Tried the version you suggested but that just threw another error: `TypeError: rawArgv2.replace is not a function`

**Comment by rstainsby** [comment]
> I tried using the latest release `0.11.0-future.1` and it seems like the issue does not happen there. Only with `0.10.0`. Should automatically be fixed once it's released then! Probably resolved due to #250

This worked for me, I used '0.11.0-next.1' with SvelteKit + the Svelte CSF add-on. Thanks!

**Comment by hatealgebra** [comment]
> > I tried using the latest release `0.11.0-future.1` and it seems like the issue does not happen there. Only with `0.10.0`. Should automatically be fixed once it's released then! Probably resolved due to #250
> 
> Tried `0.11.0-future.1` version you suggested but that just threw another error: `TypeError: rawArgv2.replace is not a function`

Hi, did you resolve it? Just got the same error. Thanks!

**Comment by Harkunwar** [comment]
Since `0.11.0` is released, the problem seems to be resolved, doesn't occur again.

**Comment by yannbf** [comment]
Hey there everyone! It seems like this issue is solved in the latest version of the test-runner, so I'll be closing it. Thanks for your patience, and do let us know if this issue occurs again!

**Comment by pedrosousa13** [comment]
I'm still getting this error on 0.19.1 with vite + react

**Comment by yannbf** [comment]
can you provide are repro? Thanks!
