### ISSUE TITLE
Can Jest and related packages in the dependencies be upgrades to vesion 29.x.x?

### ISSUE THREAD

**Issue by rpellerin** [storybookjs/test-runner#298]
Currently, these are outdated and prevent upgrades on the projects that use `@storybook/test-runner` because of incompatible Jest typescript types.

```
        "jest": "^28.0.0",
        "jest-circus": "^28.0.0",
        "jest-environment-node": "^28.0.0",
        "jest-junit": "^14.0.0",
        "jest-playwright-preset": "^2.0.0",
        "jest-runner": "^28.0.0",
        "jest-serializer-html": "^7.1.0",
        "jest-watch-typeahead": "^2.0.0",
```

**Comment by MashaSinkevich** [comment]
Is there any chance that this can be prioritized please as now update to Jest 29+ is important due to an important fix for NodeJS memory leek (see https://jestjs.io/docs/29.0/configuration/#workeridlememorylimit-numberstring)?

**Comment by yannbf** [comment]
Hey everyone! Could you please try this version out and provide feedback? It upgrades all dependencies to Jest 29:

```
yarn add -D @storybook/test-runner@0.12.0--canary.319.1d0defe.0
```

**Comment by bryanjtc** [comment]
Testing in my projects with 60 component tests, everything is good. No errors.

**Comment by MashaSinkevich** [comment]
Works great for my project (1000+ tests).

**Comment by piratetaco** [comment]
can these dependencies just be set as peerDependencies? Most of the time users will already be using jest for other purposes and as long as we're compatible we don't have to gum up yarn locks or cause potential conflicts.

**Comment by yannbf** [comment]
@piratetaco that's a great question, and sorry to hear you're having troubles because of this! 

We chose to set Jest as a direct dependency for a few reasons:
1. The test-runner uses jest-playwright-preset, jest-circus and other packages which correlate to a certain version of jest, they should be coordinated.
2. The test-runner is supposed to work out of the box for projects even if they do not use Jest. Jest is supposed to be an implementation detail.

**Comment by yannbf** [comment]
Hey everyone! I'm happy to say that the test-runner now uses Jest 29, please try its beta version here:
[`v0.14.0-next.2`](https://github.com/storybookjs/test-runner/releases/tag/v0.14.0-next.2)

It will be promoted to latest once it has enough feedback regarding its stability. Thank you! <3
