### ISSUE TITLE
[Bug]: CI hangs on node 18

### ISSUE THREAD

**Issue by zkrzyzanowski** [storybookjs/test-runner#301]
### Describe the bug

When running the test runner against a non deployed storybook instance as shown in the documentation here, https://storybook.js.org/docs/react/writing-tests/test-runner#run-against-non-deployed-storybooks, the script hangs on storybook 7 + node 18.

```
 npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
```

the above hangs indefinitely and our CI will timeout after 15 minutes

this can be resolved by updating the `npx wait-on` command to `npx wait-on tcp:127.0.0.1:6006` (or whatever the correct address is for the `http-server`

 ```
 npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
```

we have a solution, but mostly adding this bug for anyone else who might run into this issue or if maintainers want to add this to documentation for node 18 if it's truly a bug.

### To Reproduce

https://github.com/zkrzyzanowski/storybook-hangs-node-18

### System

```shell
**note** this happens on our CI as well on a linux os

Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Edge: 111.0.1661.62
    Firefox: 112.0.1
    Safari: 15.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.7 => 7.0.7
    @storybook/addon-interactions: ^7.0.7 => 7.0.7
    @storybook/addon-links: ^7.0.7 => 7.0.7
    @storybook/blocks: ^7.0.7 => 7.0.7
    @storybook/react: ^7.0.7 => 7.0.7
    @storybook/react-vite: ^7.0.7 => 7.0.7
    @storybook/test-runner: 0.10.0 => 0.10.0
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by bmstefanski** [comment]
Thanks, what's weird it works perfectly fine without `npx wait-on tcp:127.0.0.1:6006` on Gitlab :/

**Comment by mamaredo** [comment]
I get the same problem with node 18 + storybook@6.5.8.
I got around the Error by setting the `wait-on http://127.0.0.1:6006` but glad to know there are other ways!
Hopefully the documentation will be corrected.

**Comment by hananina** [comment]
Thanks!!!! it worked for me perfectly✨

**Comment by GNRSN** [comment]
Thanks! This did the trick for me as well

**Comment by m0tr0m** [comment]
Thx, for me too!!! :)

**Comment by eternalconcert** [comment]
Really great, thanks!

**Comment by JJ-Kamminga** [comment]
Had this same problem with Node 18 and Github Actions. Would be great if the documentation was corrected, as it stands it doesn't work with the latest stable version of Node. Especially annoying because it simply hangs in the CI indefinitely without any feedback.

**Comment by DaveBitter** [comment]
Even though this didn't end up fixing my issue, I'd like to use this issue to potentially help others. For me, changing `localhost` to `127.0.0.1` and adding `127.0.0.1` to the wait-on seems to do the trick:

`test-storybook --url localhost:9001/` -> `test-storybook --url http://127.0.0.1:9001/`
and
`wait-on tcp:9001` -> `wait-on tcp:127.0.0.1:9001`

**Comment by zqylur** [comment]
Is there any update to this? The workarounds provided worked for node v18.14.2, but the issue is recurring in node v20. Is there more detail on why this fix is needed? Or suggestions for debugging this issue?

**Comment by mariela-plaza** [comment]
We are experiencing the same issue with node 20.11 and storybook version 8.0.7, storybook test runner version 0.17.0. It was working fine until a couple of days ago and now the tests just stay idle until you forcibly stop the console.

Are there any suggestions / updated in regards to this issue? Thanks everyone!
