### ISSUE TITLE
[Bug] page.goto: net::ERR_UNSAFE_PORT when running on port other than 6006

### ISSUE THREAD

**Issue by work933k** [storybookjs/test-runner#307]
### Describe the bug

If i run the test-runner on port 6000, i get an error from Chromium. 
```
 page.goto: net::ERR_UNSAFE_PORT at http://localhost:6000/iframe.html\n' +
    '    =========================== logs ===========================\n' +
    '    navigating to "http://localhost:6000/iframe.html", waiting until "load"\n' +
    '    ============================================================\n' +
```
I run the test-runner as follows:
`npx start-server-and-test 'http-server --silent --port 6000 dist/storybook/shared-pipes' 'http://localhost:6000/' 'test-storybook --url http://localhost:6000 --index-json --config-dir libs/shared/pipes/.storybook'`

### Screenshots and/or logs

```
at defaultPrepare (node_modules/@storybook/test-runner/dist/cjs/setup-page.js:27:14)
      at setupPage (node_modules/@storybook/test-runner/dist/cjs/setup-page.js:79:11)
      at CustomEnvironment.setup (node_modules/@storybook/test-runner/playwright/custom-environment.js:9:5)
```

### Environment

 - OS: [e.g. iOS] Linux, WSL
 - Node.js version: [e.g. v12.17.0] v18.14.1
 - NPM version: [e.g. 6.14.4]  v9.3.1
 - Browser (if applicable): [e.g. chrome, safari]   Chrome
 - Browser version (if applicable): [e.g. 22]
 - Device (if applicable): [e.g. iPhone6] Windows 11 , WSL

### Additional context

N/A

**Comment by yannbf** [comment]
Hey @work933k thanks for opening this issue.

Amongst many other ports, [Chrome determines that port 6000 is unsafe](https://superuser.com/a/188070), so even just running Storybook wouldn't work (at least it does not for me). This is purely a Chrome issue, which is used by Playwright, which is what the test-runner uses.

Unfortunately there's nothing we can do, but you can change the port to be anything else, as long as it does not match the port from the list I mentioned previously. Thanks once again, I'll close this issue.
