### ISSUE TITLE
[bug] MDX Story interaction (play function) no longer being tested after upgrade to v7 (regression)

### ISSUE THREAD

**Issue by jukefr** [storybookjs/test-runner#312]
**Describe the bug**
Interactions from MDX (v2) stories are no longer picked up by test-runner after upgrade to storybook 7 and test runner 0.10

**To Reproduce**
Create an MDXv2 story and add a play function to it.
It works fine in the storybook ui.
Run the test runner (with stories.json mode). It is not detected/ran.

**Expected behavior**
It should pick up the fact that there is a play function in the story and run it when testing. It works perfectly fine on the storybook ui.

**System**
```
Environment Info:

  System:
    OS: Linux 6.x undefined
    CPU: irrelevant
  Binaries:
    Node: 20.2.0 - irrelevant
    npm: 9.6.7 - irrelevant
  Browsers:
    irrelevant
  npmPackages:
    @storybook/addon-a11y: ^7.0.20 => 7.0.20 
    @storybook/addon-actions: ^7.0.20 => 7.0.20 
    @storybook/addon-essentials: ^7.0.20 => 7.0.20 
    @storybook/addon-interactions: ^7.0.20 => 7.0.20 
    @storybook/addon-jest: ^7.0.20 => 7.0.20 
    @storybook/addon-links: ^7.0.20 => 7.0.20 
    @storybook/addon-mdx-gfm: ^7.0.20 => 7.0.20 
    @storybook/addon-storyshots: ^7.0.20 => 7.0.20 
    @storybook/addon-storysource: ^7.0.20 => 7.0.20 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/mdx2-csf: ^1.1.0 => 1.1.0 
    @storybook/react: ^7.0.20 => 7.0.20 
    @storybook/react-webpack5: ^7.0.20 => 7.0.20 
    @storybook/test-runner: ^0.10.0 => 0.10.0 
    @storybook/testing-library: ^0.1.0 => 0.1.0 
```

**Additional context**
Used to work fine in storybook 6.5.x and runner 0.9.3 with mdx2 preview setting on.

**Comment by gentlyawesome** [comment]
I'm also having this issue

**Comment by yannbf** [comment]
Hey there! A lot has changed since Storybook 6.5, we are now with Storybook 8.1, where authoring MDX stories changed completely. The test-runner changed together with it, and it does not support testing docs stories. Unfortunately, there are no plans to backtrack older versions of the test-runner to try and implement new features/fixes to it. Please upgrade if you can 🙏
