### ISSUE TITLE
Test runner not working with storiesOf format

### ISSUE THREAD

**Issue by ChristianTumamo** [storybookjs/test-runner#314]
I am using an older version of storybook with the 'storiesOf' format for all stories. 

I installed the test-runner and ran yarn test-storybook. All my stories are failing and the error message says that it's because I am using 'storiesOf'. Here's the message: 

`Unexpected 'storiesOf' usage: (line 120, col 0). In SB7, we use the next-generation 'storyStoreV7' by default, which does not support 'storiesOf'. `

My goal: To be able to get a report of all failed story tests without having to check each story 1 by 1 on the browser (I am currently running storybook a11y and have some tests running)

What do I need to do for it to work with storiesOf?

I am using storybook version 5.3.21

**Comment by yannbf** [comment]
Hey @ChristianTumamo!

Unfortunately the Storybook test-runner does not support Storybook 5. It got introduced alongside with Storybook 6.4.
You're currently using a version that is outdated by over 3 years. Storybook is currently at version 7.0.21, soon to be 7.1.0.

I'd highly recommend you to upgrade to Storybook 7 if you can. Given that your version is incredibly outdated, I'd recommend removing Storybook and installing it from scratch (but keeping your stories), and then slowly adjusting what is necessary.

There are migration guides and codemods that can help you migrate from storiesOf, and you can find them here:
https://storybook.js.org/docs/react/migration-guide#storiesof-to-csf

With Storybook 7 and the test-runner, you will definitely be able to achieve this (check [these docs](https://storybook.js.org/docs/react/writing-tests/accessibility-testing)):
> My goal: To be able to get a report of all failed story tests without having to check each story 1 by 1 on the browser (I am currently running storybook a11y and have some tests running)

I hope this helps!
