### ISSUE TITLE
[bug] TypeScript error when upgrading playwright to 1.35.0

### ISSUE THREAD

**Issue by tisoap** [storybookjs/test-runner#317]
**Describe the bug**
I'm using `@storybook/test-runner` with `axe-playwright`. If I upgrade my `playwright` dependency to version `1.35.0`, I get a TypeScript type error on the `.storybook/test-runner.ts` file.

TS error messages (anonymizing the full project path to just `/project/...`):

On `preRender` `injectAxe` call:
```
Argument of type 'import("/project/node_modules/playwright-core/types/types").Page' is not assignable to parameter of type 'import("/project/node_modules/playwright/node_modules/playwright-core/types/types").Page'.
```

On `postRender` `checkA11y` call:
```
Argument of type 'import("/project/node_modules/playwright-core/types/types").Page' is not assignable to parameter of type 'import("/project/node_modules/playwright/node_modules/playwright-core/types/types").Page'.
  The types returned by 'evaluateHandle(...)' are incompatible between these types.
    Type 'Promise<ElementHandle<any> | JSHandle<any>>' is not assignable to type 'Promise<JSHandle<any> | ElementHandle<any>>'.
      Type 'ElementHandle<any> | JSHandle<any>' is not assignable to type 'JSHandle<any> | ElementHandle<any>'.
        Type 'ElementHandle<any>' is not assignable to type 'JSHandle<any> | ElementHandle<any>'.
          Type 'import("/project/node_modules/playwright-core/types/types").ElementHandle<any>' is not assignable to type 'import("/project/node_modules/playwright/node_modules/playwright-core/types/types").ElementHandle<any>'.
            The types returned by '$(...)' are incompatible between these types.
              Type 'Promise<ElementHandleForTag<any> | null>' is not assignable to type 'Promise<ElementHandle<HTMLElement | SVGElement> | null>'.
                Type 'ElementHandleForTag<any> | null' is not assignable to type 'ElementHandle<HTMLElement | SVGElement> | null'.
                  Type 'ElementHandleForTag<any>' is not assignable to type 'ElementHandle<HTMLElement | SVGElement>'.
                    Types of property 'waitForSelector' are incompatible.
                      Type '{ <K extends keyof HTMLElementTagNameMap>(selector: K, options?: ElementHandleWaitForSelectorOptionsNotHidden | undefined): Promise<...>; (selector: string, options?: ElementHandleWaitForSelectorOptionsNotHidden | undefined): Promise<...>; <K extends keyof HTMLElementTagNameMap>(selector: K, options: ElementHandleWa...' is not assignable to type '{ <K extends keyof HTMLElementTagNameMap>(selector: K, options?: ElementHandleWaitForSelectorOptionsNotHidden | undefined): Promise<...>; (selector: string, options?: ElementHandleWaitForSelectorOptionsNotHidden | undefined): Promise<...>; <K extends keyof HTMLElementTagNameMap>(selector: K, options: ElementHandleWa...'. Two different types with this name exist, but they are unrelated.
                        Types of parameters 'options' and 'options' are incompatible.
                          Type 'ElementHandleWaitForSelectorOptions' is not assignable to type 'ElementHandleWaitForSelectorOptionsNotHidden'.
```

**To Reproduce**
1. Follow the steps on the [Automate accessibility tests with Storybook](https://storybook.js.org/blog/automate-accessibility-tests-with-storybook/) blog to have a `test-runner` file configured to run Axe on all stories
2. Type the[ Test Runner file ](https://storybook.js.org/docs/react/writing-tests/test-runner) with `TestRunnerConfig` type
3. Install the latest `playwright` as a `devDependency`

**Expected behavior**
I'd expect no type errors.

**Screenshots**
![Captura de Tela 2023-06-19 às 18 27 29](https://github.com/storybookjs/test-runner/assets/28565117/36dbfca0-eb27-4ffa-8f12-9f1e96c3cf96)

**System**
  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.5
  npmPackages:
    @storybook/addon-a11y: ^7.0.22 => 7.0.22 
    @storybook/addon-essentials: ^7.0.22 => 7.0.22 
    @storybook/addon-styling: ^1.3.0 => 1.3.0 
    @storybook/react: ^7.0.22 => 7.0.22 
    @storybook/react-vite: ^7.0.22 => 7.0.22 
    @storybook/test-runner: ^0.11.0-next.1 => 0.11.0-next.1 
    @storybook/testing-library: ^0.1.0 => 0.1.0 
    @storybook/testing-react: ^2.0.1 => 2.0.1

**Additional context**
There are no type errors when using `playwright` on version `1.34.3`. My full `.storybook/test-runner.ts` file is as follows:

```ts
import { injectAxe, checkA11y } from "axe-playwright";
import type { TestRunnerConfig } from "@storybook/test-runner";

const a11yConfig: TestRunnerConfig = {
  postRender: async page => {
    await checkA11y(page, "#storybook-root", {
      detailedReport: true,
      detailedReportOptions: {
        html: true,
      },
      verbose: false,
    });
  },
  preRender: async page => {
    await injectAxe(page);
  },
};

module.exports = a11yConfig;
```

**Comment by bryanjtc** [comment]
Storybook has playwright as internal dependency. Try reinstalling the @storybook/test-runner to update that playwright version or modify it directly in the lockfile.

**Comment by yannbf** [comment]
Hey @tisoap this seems like a dependency issue, please try deleting your lock file and reinstalling, or like Bryan said, update the version directly in the lock file. I'll be closing this issue, but feel free to reopen it in case this does not fix your issue. Thank you!
