### ISSUE TITLE
Set up argument parsing in CLI

### ISSUE THREAD

**Issue by shilman** [storybookjs/test-runner#32]
We currently support all Jest CLI arguments and pass them directly to Jest.

Per @ghengeveld 's suggestion, let's prune these down to the set that we want to support. That way if users want other options, they can make feature requests and we can add them as we see fit.

Being more disciplined about this helps us understand which features users want, and also allows us to switch off Jest in the future should we see fit.

**Comment by yannbf** [comment]
Fixed in #41
