### ISSUE TITLE
[bug] SWC introduction in v0.11.0 increases bundle size and leads to Nextjs API functions deployment failures.  

### ISSUE THREAD

**Issue by jeremytenjo** [storybookjs/test-runner#325]
Deploying Nextjs apps that contain API routes fail because SWC package sizes are big.

The following error occurs when deploying the Nextjs app.

![image](https://github.com/storybookjs/test-runner/assets/25231946/e08c4bb3-27db-4bed-b5ed-2bcb32a4ff48)

Leads to 

![image](https://github.com/storybookjs/test-runner/assets/25231946/88fac63d-6704-4756-9a3e-5837fe666cd0)

**Additional context**
I had to downgrade to v0.10.0. 

This issue shows the broader effects of SWC in Nextjs apps.

https://github.com/vercel/next.js/issues/42641

Thanks! :)

**Comment by bryanjtc** [comment]
SWC is only used for transforming tsx, js, ts, jsx files. Why it is related to your next.js app? Is your next.js app bundling @storybook/test-runner ?

**Comment by jeremytenjo** [comment]
I got it to work with the following `outputFileTracingExcludes` values in the `next.config.js` (Nextjs v13.4.8)

```js
   experimental: {
      outputFileTracingExcludes: {
        '*': [
          'node_modules/@swc/core-linux-x64-gnu',
          'node_modules/@swc/core-linux-x64-musl',
          'node_modules/@esbuild/linux-x64',
        ],
      },
    },
