### ISSUE TITLE
[quesiton] Test runner & chromatic coordination

### ISSUE THREAD

**Issue by ChristianTumamo** [storybookjs/test-runner#327]
**Describe the bug**
I have installed storybook test runner and axe-playwright to include accessibility tests when my test runner executes. I know it is possible to have interaction tests appearing in chromatic, but is it possible to have accessibility checks from axe-playwright and test runner appear in chromatic?

**Comment by yannbf** [comment]
Hey there @ChristianTumamo! Thanks for opening an issue here, and for using the test-runner!

The Storybook test-runner does not relate to Chromatic, although they work well in tandem. Your question is more like a feature request to Chromatic, so I would suggest reaching out to their customer support to share your thoughts! I believe they are taking this into consideration already, but it doesn't hurt to show your appreciation for such feature in their app!
