### ISSUE TITLE
jest-dom methods availability

### ISSUE THREAD

**Issue by mojereliev** [storybookjs/test-runner#33]
Hi guys! Thanks for your work.
Can you help me with a receipt for jest-dom methods availability?

`test-runner-jest.config.js`:
```
import '@testing-library/jest-dom';

module.exports = {
  setupFilesAfterEnv: ['<rootDir>/jest-setup.js'],
};
```

`story.js`:

```
import { expect } from '@storybook/jest';

...

// Inside `play` method:
expect(canvas.getByTestId('my-element-1')).toBeNull();
expect(canvas.getByTestId('my-element-2')).toBeVisible();
```

`toBeNull` — is worked;
`toBeVisible` — Is not worked: is not a function

I want to get `jest-dom` methods for `expect`, but how to do it right, can you help me? Sorry for the interruption.

**Comment by dafonov** [comment]
Im not entirely clear on what you are trying to achieve, but you could use expect(whatever).not.toBeNull() if toBeNull() doesnt throw.

**Comment by mojereliev** [comment]
I am trying to get `jest-dom` methods inside my tests. `toBeNull` is exist inside `@storybook/jest`, but `toBeVisible` is not existing

**Comment by yannbf** [comment]
Hey @mojereliev thanks for using this library! Although the test-runner takes jest configurations, what you're trying to do in your example is more for jsdom related tests. 

To get the jest-dom helpers working in your browser (that's essentially where the stories will run in the test-runner), there's no out of the box config at the moment. It's a feature we're still discussing how to better support, could be part of `@storybook/jest`, `@storybook/expect` or a preset to `@storybook/addon-interactions`. In the meantime, you could do [the following steps](https://github.com/storybookjs/storybook/discussions/16858#discussioncomment-1728871) to achieve what you're looking for, and leave the test-runner with the default configuration.

Also, watch https://github.com/storybookjs/jest/issues/7 for updates on that feature! Thanks <3

**Comment by mojereliev** [comment]
Thanks for your help and for your work!

**Comment by yannbf** [comment]
Hey @mojereliev I'm happy to announce that this has been implemented and you can access it by upgrading your `@storybook/jest` dependency to `0.0.9`! You might have to delete your package-lock or yarn.lock files as this library depends on `@storybook/expect` and should use its latest version `27.5.2-0`.

**Comment by IanVS** [comment]
FWIW, you shouldn't have to delete your whole lockfile, you can instead run `npm upgrade @storybook/expect`, which will update the sub-dependency without changing all your other dependencies as well.
