### ISSUE TITLE
[Feature Request] Support mdx

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/test-runner#36]
All my stories are in mdx format.
It would be great if I could run all the play function tests therein automatically and during the ci pipeline.

I tried using `--stories-json`, but the runner still did not find any tests...

**Comment by shilman** [comment]
@bodograumann is there a `stories.json` file when you browse `<your_sb_url>/stories.json`? that should be a valid workaround for MDX stories, so if it's not working I'd love to get to the bottom of it.

**Comment by bodograumann** [comment]
Indeed, @shilman, I have enabled the `buildStoriesJson` feature flag to get the `stories.json` (not storyStoreV7 though).
There was a change in the output, but still no tests were found apparently.

Without `--stories-json`:
```
> npm run storybook:test           

> my-app@2.4.0 storybook:test
> test-storybook

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/bodo/my-app
  323 files checked.
  testMatch: **/*.stories.[jt]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 323 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
```

With `--stories-json`:
```
> npm run storybook:test

> my-app@2.4.0 storybook:test
> test-storybook -- --stories-json

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/bodo/my-app
  401 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 8 matches
  testPathIgnorePatterns: /node_modules/ - 401 matches
  testRegex:  - 0 matches
Pattern: --stories-json|--config|/home/bodo/my-app/node_modules/@storybook/test-runner/test-runner-jest.config.js - 0 matches
```

**Comment by yannbf** [comment]
Hey @bodograumann is there a chance you're using v0.0.1? If so, can you try v0.0.2-next.4 and run the same command?

**Comment by yannbf** [comment]
BTW thank you a lot for trying this library! It's incredible how active you are around the storybook community and we really appreciate that!!

**Comment by bodograumann** [comment]
Thank you for saying that, @yannbf  :relaxed: 

You were right with your guess. I had, kind of blindly, followed the installation instructions and of course gotten only version 0.0.1.
With 0.0.2-next.4 and using `--stories-json` the tests are all run :heart:.

I am leaving this ticket open for first-level mdx support, but for now this is already a good solution for us. :rocket:

**Comment by danspratling** [comment]
Are there any updates on this? I'm trying to test (local) stories from MDX files (accessibility & interactions)

The tests run within storybook fine, but don't run using test runner

I'm currently on v0.1.1

When I enable the `buildStoriesJson` flag in `storybook/main.js` it this throws an error when running storybook - without it I always get the above no stories found error

```
.../node_modules/file-system-cache/lib/common/Util.js:66
            throw new Error(`Failed to read cache value at: ${path}. ${error.message}`);
```

**Comment by yannbf** [comment]
Hey peeps! I'm closing this ticket given that direct MDX support is not in our plans. You can achieve your tests by using `--stories-json` or `--index-json` (if you're using newer versions of test-runner). Thank you!
