### ISSUE TITLE
Can you trigger a test run programmatically?

### ISSUE THREAD

**Issue by mlshohet** [storybookjs/test-runner#362]
Dear SB Test Runner devs: First of all, I love it! Thanks for all your work, it is quite amazing.

I was wondering if there is a way to run the test-runner not from CLI or package, but from another script. Is there something like an executable that can be imported and then maybe configured?

Much thanks for any help!

**Comment by yannbf** [comment]
Hey there @mlshohet! Thank you for your kind words.

You can potentially run the test-runner via its `test-storybook` binary. Not sure exactly what you're trying to achieve, but here's an example that hopefully helps you get started with:

```ts
const { spawn } = require('child_process');

const testRunnerBinaryPath = './node_modules/.bin/test-storybook';
const binaryArgs = ['--verbose']; // Replace with your actual arguments

const childProcess = spawn('node', [testRunnerBinaryPath, ...binaryArgs], {
    stdio: 'inherit', // change if you want the output to be ignored or piped
});

childProcess.on('error', (err) => {
    console.error(`Error when running the Storybook test-runner: ${err}`);
});

childProcess.on('exit', (code) => {
    if (code === 0) {
        console.log(`Storybook tests ran successfully.`);
    } else {
        console.error(`The Storybook test-runner exited with an error code: ${code}`);
    }
});
```

**Comment by mlshohet** [comment]
@yannbf This is perfect. Thank you for the sweet example and for the time; very generous! All the best!

**Comment by yannbf** [comment]
No worries, have a great one and thank you for using the test-runner!
