### ISSUE TITLE
[question] Are we able to access Playwright globals in test execution?

### ISSUE THREAD

**Issue by omacranger** [storybookjs/test-runner#365]
Howdy! 

As the title suggests, are we able to access Playwright globals (such as `page`) while in test-runner play execution (either in the browser or in test-runner CLI)? I can't seem to get it to work, though jest-playwright's seem to so that is available.

**Comment by yannbf** [comment]
Hey @omacranger! The Storybook test-runner works in the following way:
1. You run your Storybook
2. The test-runner accesses your stories in the browser using Playwright
3. Once a story is visited, the play function is executed. This step is fully in the browser, and the test-runner doesn't do anything other than "watch it happen". You can't do anything here via the test-runner. You can do so via the play function of your story, but that is completely detached from Playwright.
4. After that is done, the [postRender](https://github.com/storybookjs/test-runner#experimental-test-hook-api) hook is executed, and you have access to the Page instance.
5. After all of that, the test-runner reports success or failure for a given story

**Comment by omacranger** [comment]
Appreciate the clarification, thanks @yannbf !
