### ISSUE TITLE
[question] How can I implement the equivalent of before/after each? 

### ISSUE THREAD

**Issue by sw-tracker** [storybookjs/test-runner#371]
I would like to be able to perform some tasks before and after each test, i.e. clear/set localstorage, etc.

How can I do this with storybook interaction testing?

**Comment by realappie** [comment]
Hey there, for beforeEach I tend to use the `decorators` function, which is called on each render of the story

```typescript
const mock = jest.fn();

const componentMeta: ComponentMeta<SomeComponenet> = {
    title: 'Some component',
    component: SomeComponenet,
    decorators: [
        Story => {
            mock.mockClear();
            return <Story />;
        },
    ],
};

export default componentMeta;

export const shouldDoStuff: ComponentStoryObj<SomeComponenet> = {
    play: async ({ canvasElement }) => {
      // do stuff that calls mock....
      expect(mock).toBeCalled();
    },
};

export const shouldDoOtherStuff: ComponentStoryObj<SomeComponenet> = {
    play: async ({ canvasElement }) => {
      // do nothing
      expect(mock).toBeCalled(); // will give you an error, as it was cleared in the 'decorators' above
    },
};



```

**Comment by sw-tracker** [comment]
Hi @realappie , thank you for the tip. We are doing something very similar for the beforeEach at the moment in our components. However, it is custom made and not intuitive. We also dont have a solution for the afterEach yet.

I think Storybook should provide a beforeEach and an afterEach for each component. This would align it with many other testing frameworks.

**Comment by yannbf** [comment]
Hey everyone! Thanks for opening this issue. That's definitely something we are considering implementing, but unfortunately such functionality isn't built in in Storybook.

However! You can achieve something very similar, by using Storybook's existing concepts. Let me map them out for you.

### BeforeAll - Storybook preview.js file

The preview file is called once, in Storybook. It's useful to load global configuration like css, etc. This is a good place for a "beforeAll" implementation.

### BeforeEach - Storybook loaders

[Storybook loaders](https://storybook.js.org/docs/web-components/writing-stories/loaders#page-top) are executed before the story renders. They can be set globally in preview, or per component on meta, or per story. This is a good place for a "beforeEach" implementation.

### AfterEach - End of the Storybook play function

The play function is executed after the story renders. That's where you will add your interactions or test code, and after all of it is executed, it would be the best place to clean up. Therefore, you could add a "cleanup" step at the end of your play function.

### Code snippets

Here's an example that shows a complete use case with all of these potential hooks:

```ts
// .storybook/preview.ts
import { configure } from '@storybook/testing-library'
import { expect } from '@storybook/jest'

// Scenario: preconfiguring testing-library globally
configure({ testIdAttribute: 'data-test' })

// Scenario: extending expect globally with a custom matchers
expect.extend({
  toBeANumber(received) {
    const pass = typeof received === 'number'
    if (pass) {
      return {
        message: () => `expected ${received} not to be a number`,
        pass: true,
      }
    } else {
      return {
        message: () => `expected ${received} to be a number`,
        pass: false,
      }
    }
  },
})

console.log("[HOOK] BEFORE ALL - GLOBAL")
```


```ts
// Button.stories.ts
import { StoryObj, Meta } from '@storybook/react'
import { expect, jest } from '@storybook/jest'
import { userEvent, within } from '@storybook/testing-library'

import { Button } from './Button'

let clickSpy = jest.fn()

const meta = {
  component: Button,
  args: {
    children: 'Button',
    onClick: clickSpy,
  },
  // loaders are called before a story renders
  // if put in the meta, they will be equivalent to a "beforeEach"
  // if put in the story, they will be equivalent to a "beforeStory"
  loaders: [
    async (context) => {
      // you use context to check story annotations like args, etc, if you'd like.
      // clean up mock usage between stories
      clickSpy.mockClear()
      clickSpy.mockImplementation(() => console.log('foobar', context))
      console.log('[HOOK] BEFORE EACH - BUTTON')
      return {}
    },
  ],
  play: async () => {
    console.log('[HOOK] AFTER EACH - BUTTON')
  },
} satisfies Meta<typeof Button>
export default meta

type Story = StoryObj<typeof meta>

// here, the "beforeEach" will be called because of the loader
export const Default: Story = {
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement)
    const button = await canvas.findByRole('button')
    await userEvent.click(button)
    await expect(args.onClick).toHaveBeenCalledTimes(1)

    // but the "afterEach" will have to be called manually
    // given that this story overrides the play function
    await meta.play()
  },
}

// here, the "beforeEach" and "afterEach" will be called
export const Disabled: Story = {
  args: {
    disabled: true,
  },
}
```
--- 

I know this is not amazing, but should be enough to unblock you while we work on proper APIs for these lifecycle hooks!
