### ISSUE TITLE
[dependencies] Axios Cross-Site Request Forgery Vulnerability

### ISSUE THREAD

**Issue by seanmc86** [storybookjs/test-runner#386]
Dependabot has reported a new moderate vulnerability stemming from axios. This vulnerability is not automatically resolvable, and manually overriding the version of axios to the fixed version below causes an error when running "test-storybook"

![image](https://github.com/storybookjs/test-runner/assets/26269961/a86152a8-238a-45fa-80a5-d2ec52d76d79)

![image](https://github.com/storybookjs/test-runner/assets/26269961/b02d4a46-ade3-4d4b-a406-91aa180b1a01)

**Comment by yannbf** [comment]
Hey there @seanmc86! Thank you for reporting.

That's quite weird, as axios is a dependency of wait-on, which is only used as dev dependency of the test-runner, not direct dependency. Regardless, I updated wait-on to fix this issue for the test-runner codebase [here](https://github.com/storybookjs/test-runner/pull/389), and it will be included in a patch release soon, maybe it helps?

**Comment by prstn** [comment]
Thank you for the quick update!
 
I am still seeing the issue after installing `"@storybook/test-runner": "^0.14.2-next.0"` – looks like it is because of `jest-playwright-preset` and it's subsequent dependencies (jest-playwright-preset -> jest-process-manager -> wait-on -> axios`  
```
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/jest-process-manager/node_modules/axios
  wait-on  5.0.0-rc.0 - 7.1.0
  Depends on vulnerable versions of axios
  node_modules/jest-process-manager/node_modules/wait-on
    jest-process-manager  *
    Depends on vulnerable versions of wait-on
    node_modules/jest-process-manager
      jest-playwright-preset  >=1.0.0-rc1
      Depends on vulnerable versions of jest-process-manager
      node_modules/jest-playwright-preset
        @storybook/test-runner  *
        Depends on vulnerable versions of jest-playwright-preset
        node_modules/@storybook/test-runner
```

**Comment by dougalg-js-tw** [comment]
@prstn good note on `jest-playwright-preset` which was last published a year ago, and seems unmaintained. In fact, [they recommend migrating](https://www.npmjs.com/package/jest-playwright-preset) to [@playwright/test](https://playwright.dev/docs/test-intro)
