### ISSUE TITLE
[bug] I suspect the --failOnConsole parameter doesn't work any more.

### ISSUE THREAD

**Issue by work933k** [storybookjs/test-runner#410]
**Describe the bug**
I run test-storybook with the `--failOnConsole` parameter, but the tests pass even while there are errors in the browser-console.

**To Reproduce**
`test-storybook --url http://localhost:6006 --index-json --failOnConsole   --config-dir libs/dummy-app/shared/choose-product-date/.storybook`

@storybook/test-runner@0.16.0

**Output**
```
Running command: test-storybook --url http://localhost:6006 --index-json --failOnConsole   --config-dir libs/dummy-app/shared/choose-product-date/.storybook
Serving "dist/storybook/dummy-app-shared-choose-product-date" at "http://localhost:6006/"
[test-storybook] Cleaning up /tmp/86f0791b657a5727a17427b83e310a61
 PASS   browser: chromium  ../../tmp/86f0791b657a5727a17427b83e310a61/pensionpostponecomponent.test.js
 PASS   browser: chromium  ../../tmp/86f0791b657a5727a17427b83e310a61/participationdetailcomponent.test.js
 PASS   browser: chromium  ../../tmp/86f0791b657a5727a17427b83e310a61/pensionbringforwardcomponent.test.js
 PASS   browser: chromium  ../../tmp/86f0791b657a5727a17427b83e310a61/choosepensiondatecomponent.test.js
 PASS   browser: chromium  ../../tmp/86f0791b657a5727a17427b83e310a61/participationapplychoicescomponent.test.js

Test Suites: 5 passed, 5 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        5.682 s
Ran all test suites.
```

It used to work before.

**Comment by matttk** [comment]
We also ran into this yesterday. Tried `console.log` in various places and it never works anywhere.

**Comment by yannbf** [comment]
Hey there @matttk @work933k could you provide a reproduction? I just tested the flag in two different projects and it works as intended. The flag is only intended to fail on `console.error` calls during the rendering or play function, btw.

**Comment by sunilrathore24** [comment]
@yannbf correct me if i am wrong, in my angular application i am getting console error regarding missing component since i have not added, but when i run

**Comment by work933k** [comment]
I'm using test-storybook in a NX-workspace. I've created a simple executor which does a "build-storybook" and then serves Storybook using Express. On this instance the executor runs test-storybook. Using this custom executor the `--failOnConsole` parameter does not work. But when i run `storybook` and then manually run test-storybook on that storybook-hosting-instance, the --failOnConsole does work.

I suspect that build-storybook does some optimizations which prevent the console errors to be caught.

**Comment by work933k** [comment]
I think this issue might be closed. The "failOnConsole" option seems to work. Although it only works with Angular with Storybook when build NOT in production-mode. In NX this is controlled with the option enableProdMode=false.
