### ISSUE TITLE
[question] Error: Cannot find module 'detect-package-manager'

### ISSUE THREAD

**Issue by y-temp4** [storybookjs/test-runner#414]
It seems that when running tests for a Storybook managed in a separate package, with a package.json that only includes `@storybook/test-runner`, `concurrently`, and `wait-on` as dependencies, an error occurs stating `Error: Cannot find module 'detect-package-manager'`.

I suspect this error is due to `detect-package-manager` being included in the `devDependencies` of `@storybook/test-runner`, rather than in its `dependencies`.

The version of `@storybook/test-runner` being used is `0.16.0`.

**Comment by yannbf** [comment]
Hey everyone! In the most recent versions of the test-runner (0.18.0), neither `semver` nor `detect-package-manager` are used anymore, so this problem should go away. Please upgrade whenever you can! Thanks <3
