### ISSUE TITLE
Installation Error with NPM

### ISSUE THREAD

**Issue by MohammedNagdy** [storybookjs/test-runner#433]
**Describe the bug**
The `test-runnner` package cannot be installed using `npm` although the storybook [documents](https://storybook.js.org/docs/writing-tests/test-runner) say it's possible.

**To Reproduce**

1. Create an npm project.
2. Attempt installing the package `$ npm install --save-dev @storybook/test-runner`
3. You will get the error unsupported protocol 
   ```
   npm ERR! code EUNSUPPORTEDPROTOCOL
   npm ERR! Unsupported URL Type "link:": link:..

   npm ERR! A complete log of this run can be found in:
   ```

**Expected behavior**
It should easily install the package to the dependency tree.

**System**
MacOS Monterey 12.6.1

**Temporary solution**
This issue can be solved by installation using `yarn` `yarn add --dev @storybook/test-runner`. But please update the documentations to not cause further headache for other developers. Thanks!

**Comment by yannbf** [comment]
Hey there @MohammedNagdy, thanks for reporting the issue. I have never seen it, and I suspect it might be related to your project's package.json. Could you share the full log file as mentioned by NPM in the error?

**Comment by MohammedNagdy** [comment]
Thanks @yannbf It's alright though. I ran the command again and it went through this time.
