### ISSUE TITLE
[question] Any plans to support v8.0.0???? 

### ISSUE THREAD

**Issue by jorgercg** [storybookjs/test-runner#437]
When can we expect a v8.0.0 compatible version?

Thanks for the awesome work!!!!

**Comment by yannbf** [comment]
Hey there @jorgercg, the test-runner is compatible with Storybook 8! But as Storybook 8 is under a prerelease, so is the test-runner.

While Storybook 8 is not out, you can try it like so:
```
yarn add @storybook/test-runner@next
```
