### ISSUE TITLE
[feature request] Make tags available in the test context

### ISSUE THREAD

**Issue by joakimgunst** [storybookjs/test-runner#446]
Tags can currently be used to [include, exclude and skip](https://storybook.js.org/docs/writing-tests/test-runner) specific stories in the test runner. It would be nice if the tags of the story were available on the `TestContext` which is passed as the second argument to e.g. `postVisit`. This would allow custom logic based on tags.

We currently have two use cases for this: skipping accessibility tests for the story (but not all tests), and delaying execution of the accessibility tests to not get a contrast violation when a component has a fade-in transition.

**Comment by zb-sj** [comment]
You can do this with `getStoryContext` which is actually described in the doc: [Accessing story information with the test-runner](https://storybook.js.org/docs/writing-tests/test-runner#accessing-story-information-with-the-test-runner)

**Comment by joakimgunst** [comment]
Great, I didn't know that. Thank you @zb-sj!
