### ISSUE TITLE
[Playwright] Cannot find module '@storybook/testing-react' from file

### ISSUE THREAD

**Issue by yannbf** [storybookjs/test-runner#8]
### Describe the bug

When running the test-runner against .js files, I get this error:

![image](https://user-images.githubusercontent.com/1671563/145804280-5f7c9ab6-ed02-4b89-871d-511418e35fe4.png)

It should not happen because @storybook/testing-react has nothing to do with playwright.
The error goes away when the file is changed to .tsx

**Comment by shilman** [comment]
This looks like a typo in the Jest config:

```
testMatch: ['**/basic/*.stories.[jt]s?(x)'],
```

should be 

```
testMatch: ['**/basic/*.stories.[jt]s(x)?'],
```

**Comment by yannbf** [comment]
This is fixed!
