### ISSUE TITLE
[Bug] Validation Error when running yarn test-storybook

### ISSUE THREAD

**Issue by lporras** [storybookjs/test-runner#84]
### Describe the bug

I am configuring my storybook to run test-runner following this guide:
[Test runner guide](https://storybook.js.org/addons/@storybook/test-runner)

and when I run `yarn test-storybook --url http://localhost:4400`

I get an error.

```
yarn test-storybook --url http://localhost:4400
yarn run v1.22.17
$ test-storybook --url http://localhost:4400
● Validation Error:

  Option "testMatch" must be of type:
    array
  but instead received:
    string

  Example:
  {
    "testMatch": [
      "**/__tests__/**/*.[jt]s?(x)",
      "**/?(*.)+(spec|test).[jt]s?(x)"
    ]
  }

  Configuration Documentation:
  https://jestjs.io/docs/configuration

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

 - OS: OSX
 - Node.js version: v16.13.2
 - NPM version: 8.1.2

**Comment by yannbf** [comment]
Hey @lporras thanks for opening this issue! Could you please share a repro? Or show what your main.js `stories` field looks like?

**Comment by lporras** [comment]
Sorry I can not share the repo since is a private repo. I will close this Issue since I don't even remember what project it was.
