### ISSUE TITLE
[Bug] Unable to run with custom-config in an esm-project

### ISSUE THREAD

**Issue by benbender** [storybookjs/test-runner#91]
### Describe the bug

If I eject the config in an esm-project, the filename `test-runner-jest.config.js` is interpreted as esm-module and jest will fail to run. As the filename is hardcoded, I'm unable to rename the file to `test-runner-jest.config.cjs`.

### Two possible solutions:

1.  make the filename of the config adjustable via parameter 
2. test for the existance of `test-runner-jest.config.cjs` in the cli

**Comment by bryanjtc** [comment]
Fixed with #259
