### ISSUE TITLE
Include '--testPathIgnorePatterns' in the CLI Options

### ISSUE THREAD

**Issue by sambunting** [storybookjs/test-runner#95]
I have an issue at the moment where some tests are failing, and I have decided to temporarily disable them so that the whole command doesn't fail.

Jest has a CLI option called [--testPathIgnorePatterns=<regex>|[array]](https://jestjs.io/docs/cli#--testpathignorepatternsregexarray) - but it doesn't seem to work with the test runner.

When I run it - I get:
```js
test-storybook --testPathIgnorePatterns Button.stories.jsx

error: unknown option '--testPathIgnorePatterns'
Usage: test-storybook [options]
```

I'm not sure if I'm doing something wrong, or I've misunderstood how the test runner handles flags/options - I assumed that all jest options would be "carried through" to Jest.

**Comment by sambunting** [comment]
Ah. Nevermind. I think I found how to do it.... Completely missed the bit about `--eject`...

I've managed to get what I need by doing the following:

1. Run `npm run test-storybook -- --eject`. This creates a `test-runner-jest.config.js`.
2. Modify the file, to include `modulePathIgnorePatterns` - the whole file should look something like this:
```js
const { getJestConfig } = require('@storybook/test-runner');

module.exports = {
  // The default configuration comes from @storybook/test-runner
  ...getJestConfig(),
  /** Add your own overrides below
   * @see https://jestjs.io/docs/configuration
   */
  modulePathIgnorePatterns: ['Button.stories.jsx'],
};
```

**Comment by yannbf** [comment]
Great you figured that out! Ideally if you want extra flexibility you can eject the configuration.
